### PR TITLE
throw error when using plugins with components

### LINKED ISSUE #655: Include notice that plugins do not work w/ components
Users are getting confused between Components and SFV.1 and trying to add plugins to them.  We should detect if `plugins` is included and throw an error message if so.

### PR DESCRIPTION
**Pull request by eahefnawy**
Closes #655

### CODE REVIEW

File: src/cli/commands/utils.js [hunk 1]
```diff
@@ -329,6 +329,13 @@ const loadVendorInstanceConfig = async (directoryPath, options = { disableCache:
     }
   }
 
+  // give early feedback to people who are trying to use plugins with components
+  if (instanceFile.plugins) {
+    throw new Error(
+      'Serverless Framework plugins are not support by Serverless Components. Please remove the "plugins" property and try again'
```
Comment (medikoo) [inline src/cli/commands/utils.js:335]: `are not supported`

File: src/cli/commands/utils.js [hunk 2]
```diff
@@ -329,6 +329,13 @@ const loadVendorInstanceConfig = async (directoryPath, options = { disableCache:
     }
   }
 
+  // give early feedback to people who are trying to use plugins with components
+  if (instanceFile.plugins) {
+    throw new Error(
```
Comment (medikoo) [inline src/cli/commands/utils.js:334]: Shouldn't this be reported as _operational_ error? I guess throwing it with bare `Error` will make reporting obscure (with full stack trace)

Comment (eahefnawy) [reply src/cli/commands/utils.js:334]: what you mean "operational error"?! There's no stack trace by default. Here's how it looks like:

```
my-vue-app-2 node ../../../components/bin/bin deploy

Serverless › Serverless Framework Plugins are not support by Serverless Components. Please remove the "plugins" property and try again 

  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 


my-vue-app-2 
```

File: src/cli/commands/utils.js (hunk 1 above)
Comment (eahefnawy) [reply src/cli/commands/utils.js:335]: good catch 👍

File: src/cli/commands/utils.js (hunk 2 above)
Comment (medikoo) [reply src/cli/commands/utils.js:334]: > what you mean "operational error"

See "Operational errors vs. programmer errors" section here: https://www.joyent.com/node-js/production/design/errors 
It neatly explains what I mean.

> There's no stack trace by default. Here's how it looks like:

Ok, so then _programmer_ errors which can be cryptic as "undefined is not a function" are also shown with no stack trace right? It can be painful for debugging

Comment (medikoo) [reply src/cli/commands/utils.js:334]: In Framework we recognize between both error types, and _operational_ are exposed just by message, and _programmer_ errors always go with full stack trace.

(anyway that's unrelated to this PR)

**Review by medikoo — APPROVED** [review]
